//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_data
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string created_time { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string status { get; set; }
        public string source { get; set; }
        public Nullable<int> check { get; set; }
    }
}
