//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class facebookEntities : DbContext
    {
        public facebookEntities()
            : base("name=facebookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_client> tbl_client { get; set; }
        public virtual DbSet<tbl_filed_data> tbl_filed_data { get; set; }
        public virtual DbSet<tbl_post> tbl_post { get; set; }
        public virtual DbSet<tbl_userlist> tbl_userlist { get; set; }
    }
}
