//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Facebook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_client
    {
        public int id { get; set; }
        public long pid { get; set; }
        public long client_id { get; set; }
        public string created_time { get; set; }
    }
}
